spacenow:
  discord:
    token: # write discord token
spring:
  main:
    web-application-type: none
  data:
    mongodb:
      database: spacenow
  security:
    oauth2:
      client:
        registration:
          twitter:
            client-id: # write consumer key
            client-secret: # write consumer secret
            authorization-grant-type: client_credentials
        provider:
          twitter:
            token-uri: https://api.twitter.com/oauth2/token
